# Generated by Django 3.2.3 on 2022-06-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/product')),
                ('og_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('mcate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfruit.maincategorymodel')),
            ],
        ),
    ]
