# Generated by Django 3.2.3 on 2022-06-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfruit', '0003_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='total',
        ),
    ]
