# Generated by Django 3.2.3 on 2022-06-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfruit', '0005_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
