# Generated by Django 3.2.3 on 2022-07-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfruit', '0007_customeraddressmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddressmodel',
            name='user',
        ),
    ]
